env:
  node: true
root: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
rules:
  valid-jsdoc: error
  prettier/prettier: error
overrides:
  - files:
      - "**/__tests__/**"
    env:
      jest: true
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true